FROM node:21-alpine3.19

WORKDIR /usr/src/app  

COPY package.json ./
COPY package-lock.json ./  

RUN npm install




COPY tsconfig.json tsconfig.build.json ./
COPY src src



EXPOSE 3001
CMD ["npm", "run", "start:prod"] 
