
version: '3.8'
services:

      
  mysql:
    image: mysql:8.0
    container_name: mysql_nestjs
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    
    volumes:
      - ./mysql-data:/var/lib/mysql

      
